### ISSUE TITLE
installing docker-compose 

### ISSUE THREAD

**Issue by hugocoolens** [koenvervloesem/raspberry-pi-home-automation#1]
I noticed that installing docker-compose with the command sudo pip3 install docker-compose (as mentioned on page 48) does not work (results in errors), the image used is: 2020-08-20-raspios-buster-armhf-lite.
Installing docker-compose via apt-get is possible but the version is 3.3 and not 3.7.
I can send you a log of the installation via pip3 (you know how to contact me)

**Comment by koenvervloesem** [comment]
Thanks for your issue and the log! I added this to the errata.
