### ISSUE TITLE
For some RTL-SDR sticks the idProduct number is 2832 in stead of 2838

### ISSUE THREAD

**Issue by hugocoolens** [koenvervloesem/raspberry-pi-home-automation#3]
I noticed for the RTL-SDR stick I am using the line mentioned on page 162
SUBSYSTEM=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838", OWNER="pi", MODE="0660"
should be replaced by:
SUBSYSTEM=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2832", OWNER="pi", MODE="0660"

Using the original line mentioned in the book resulted in the following error message when running "docker logs -f rtl433tomqtt":
Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules

Apparently some sticks use 2838, while others 2832

**Comment by koenvervloesem** [comment]
Yes, I should have made it clear that you need to look at the values that `lsusb` shows for your device. This is now only shown _after_ the udev rule in the book.

Which model of the RTL-SDR stick is this?

**Comment by hugocoolens** [comment]
> Yes, I should have made it clear that you need to look at the values that `lsusb` shows for your device. This is now only shown _after_ the udev rule in the book.
> 
> Which model of the RTL-SDR stick is this?

Sorry but I can't tell you, I have this stick already a few years, I  removed the original case and I built it in a new aluminum case for better EMC-properties and cooling.

**Comment by koenvervloesem** [comment]
Ok, no problem, I was just curious. But I added your remark now to the errata in https://github.com/koenvervloesem/raspberry-pi-home-automation/commit/33be20fe6dd0e95a52a3b363ad1456017f9ace81. Thanks again!
