### ISSUE TITLE
install pyton foobar

### ISSUE THREAD

**Issue by Marcelklim** [koenvervloesem/raspberry-pi-home-automation#6]
on page 44 of your BookControl your Home with Raspberry Pi "sudo pip3 install foobar" i get the error 'could not find a version that satifies the required foobar. No matching distribution found for foobar. I am wotking on a raspberry pi 3B.

**Comment by koenvervloesem** [comment]
This is just a fictional name, so it's not meant to be installed. You can just go on with the rest of the book and the other times it shows a `pip3 install` command it will be with an existing package name.
